version: '2'

services:
  app:
    build: ./
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=development"

  db:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=bikeshop"
